{{- if hasKey .Values.secrets "dockerConfigJson" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cronjobs.fullname" . }}-registry
  labels:
    {{- include "cronjobs.labels" . | nindent 4 }}
  annotations:
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.dockerConfigJson }}
{{- end }}
